### ISSUE TITLE
It isn't working on Q4OS w/ KDE Plasma

### ISSUE THREAD

**Issue by felipelalli** [anselmolsm/plasma-weeknumber#6]
It says "QtQuick Module isn't installed" but it is.

**Comment by anselmolsm** [comment]
Sounds like an environment issue. The code simply imports QtQuick. Qt QuickControls missing, maybe?

FWIW  it works as expected on an updated Arch Linux + Qt 5.15 + Plasma 5.19.

**Comment by felipelalli** [comment]
I'm using Q4OS 3.11.1-n1.
KDE Plasma 5.14.5
KDE Frameworkds 5.54.0
Qt Version 5.11.3
Kernel 4.19.0-9-amd64

**Comment by anselmolsm** [comment]
I don't know Q4OS. As apparently it's Debian-based, Debian splits qml modules in [several packages](https://packages.debian.org/search?keywords=qml-module-qtquick). I guess you need qml-module-qtquick2.

Anyway, this is due to either a distro issue or misconfigured environment.

**Comment by felipelalli** [comment]
`qml-module-qtquick2 is already the newest version (5.11.3-4).`

Well, OK, thank you anyway.

**Comment by anselmolsm** [comment]
OK, this table may be the answer:  https://doc.qt.io/qt-5/qtquickcontrols-index.html#versions

This [import QtQuick 2.12 ](https://github.com/anselmolsm/plasma-weeknumber/blob/master/contents/ui/CompactRepresentation.qml#L18) won't work on Qt 5.11... which was released in May 2018. (5.12 is an LTS release, 5.11 isn't).
